const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.TiledBg,
		C3.Plugins.Sprite,
		C3.Behaviors.EightDir,
		C3.Behaviors.scrollto,
		C3.Behaviors.bound,
		C3.Behaviors.Bullet,
		C3.Behaviors.destroy,
		C3.Behaviors.Fade,
		C3.Plugins.Mouse,
		C3.Plugins.Text,
		C3.Behaviors.Anchor,
		C3.Plugins.Keyboard,
		C3.Plugins.Button,
		C3.Behaviors.Sin,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Sprite.Acts.SetTowardPosition,
		C3.Plugins.Mouse.Exps.X,
		C3.Plugins.Mouse.Exps.Y,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.Mouse.Cnds.OnClick,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Sprite.Acts.SetAngle,
		C3.Plugins.System.Exps.random,
		C3.Plugins.Text.Acts.SetVisible,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Sprite.Acts.SubInstanceVar,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.Sprite.Cnds.IsOutsideLayout,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.System.Cnds.ForEach,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.Sprite.Acts.RotateTowardPosition,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.Button.Cnds.OnClicked,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Plugins.System.Acts.SetVar
	];
};
self.C3_JsPropNameTable = [
	{Wallpaper: 0},
	{"8Direções": 0},
	{CentrarEm: 0},
	{RestritoAoLayout: 0},
	{Player: 0},
	{Vida: 0},
	{Projétil: 0},
	{Monster: 0},
	{DestruirForaDoLayout: 0},
	{Esmaecer: 0},
	{Spell: 0},
	{Mouse: 0},
	{Âncora: 0},
	{Score: 0},
	{Game_Over: 0},
	{Keyboard: 0},
	{Explosion: 0},
	{Monster2: 0},
	{Coffin: 0},
	{Wallpaper_Home: 0},
	{Senóide: 0},
	{Botton: 0},
	{Game_name: 0},
	{Wallpaper_gameover: 0},
	{Text_Restart: 0},
	{PlanoDeFundoEmBlocos: 0},
	{PlanoDeFundoEmBlocos2: 0},
	{PlanoDeFundoEmBlocos3: 0},
	{Sprite: 0},
	{Pontos: 0}
];

self.InstanceType = {
	Wallpaper: class extends self.ITiledBackgroundInstance {},
	Player: class extends self.ISpriteInstance {},
	Monster: class extends self.ISpriteInstance {},
	Spell: class extends self.ISpriteInstance {},
	Mouse: class extends self.IInstance {},
	Score: class extends self.ITextInstance {},
	Game_Over: class extends self.ITextInstance {},
	Keyboard: class extends self.IInstance {},
	Explosion: class extends self.ISpriteInstance {},
	Monster2: class extends self.ISpriteInstance {},
	Coffin: class extends self.ISpriteInstance {},
	Wallpaper_Home: class extends self.ISpriteInstance {},
	Botton: class extends self.IButtonInstance {},
	Game_name: class extends self.ITextInstance {},
	Wallpaper_gameover: class extends self.ISpriteInstance {},
	Text_Restart: class extends self.ITextInstance {},
	PlanoDeFundoEmBlocos: class extends self.ITiledBackgroundInstance {},
	PlanoDeFundoEmBlocos2: class extends self.ITiledBackgroundInstance {},
	PlanoDeFundoEmBlocos3: class extends self.ITiledBackgroundInstance {},
	Sprite: class extends self.ISpriteInstance {}
}